- integration_tests/integration/health.spec.js
- server/app.ts
Interestingly because of the redirect to HMPSS Auth Kubernetes was mostly happy, though it does a generate a load of bad probes
> Added missing ping endpoint as used by Kubernetes for liveliness probe

- .circleci/config.yml
These changes ensure the notification works out of the box and adds in a slight refactor to set a dry/reusable pattern.
> Fix the slack notification on `check_outdated`

- audit-ci.json
The "medium" configuration was not an acceptable term, should be one of "info", "low", "moderate", "high" or "critical". This meant that it would not pick up on anything!
> Fixing configuration of security audit

- .circleci/config.yml
- Dockerfile
- integration_tests/index.d.ts
- integration_tests/support/commands.ts
Need to refer to build args before calling apt-get upgrade otherwise the set of packages are cached and not upgraded. Docker cannot cache anything in layers after a dynamic variable has been used
Also bumping version of node and fixing test compilation issue
> Fixing docker caching issue

- .circleci/config.yml
This caused an issue with our build where we received a segmentation fault as soon as the integration tests called the node app. Segmentation faults generally indicate an issue with one of the native C/C++ modules and it appears that one of these modules was relying on something we have stashed in the cache (is my best guess!)
> SLM-245 Restore cache prior to running the app for the integration tests

- server/views/pages/error.njk
- server/views/pages/index.njk
The `index.njk` and `error.njk` files use `layout.njk` which extends `govuk/template.njk`. `govuk/template.njk` already includes a `<main>` element.
[According to the HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element) there should only be one `<main>` element present in the document at a time. Having multiple `<main>` elements could affect screen readers and other assistive technologies.
(NB the link in the [contributing guidelines](https://github.com/ministryofjustice/.github/blob/23444d612e846ceca655dc18c2a040c56a9f2f80/CONTRIBUTING.md) to [GDS guidance on commit hygene](https://gds-way.cloudapps.digital/standards/source-code.html#commit-messages) is dead so please let me know if there any improvements that need to be made to the commit message)
> Remove duplicate <main> elements

- server/middleware/setUpWebSecurity.ts
- server/views/partials/layout.njk
Based on what I’ve seen elsewhere, this seems to now be a common approach to allow us to inline scripts, see:
https://content-security-policy.com/nonce
The GOV.UK frontend has now been updated to support the use of the `cspNonce` local - see:
https://github.com/alphagov/govuk-frontend/commit/2e40d744af6e6e4213ebc47644982d4eb94422d4
So we no longer need to add the inline hash, which is vulnerable to if the code in the frontend template is changed.
I’ve also removed the domain-specific overrides for jQuery scripts and styles, as we can use the nonce for this too.
>  Add a `cspNonce` to the webSecurity setup

- docker-compose.yml
Which is suitable for arm64 and consistent with docker-compose-test which was updated with https://github.com/ministryofjustice/hmpps-template-typescript/pull/89
> Use official redis image for docker-compose

- .prettierrc
In eslint, we ask for a trailing comma, while the prettier rules are set to `es5`. This causes issues if you have your IDE set up to fix on save, as one linter kicks in before the other, causing conflicting fixes.
> Fix conflicting prettier / eslint rule

- server/applicationVersion.ts
- server/utils/nunjucksSetup.ts
At the moment the cache is linked to the start up time of pod, so get unnecessary cache misses for every client, for each pod in the cluster and also as pods restart
This ties the cache to the git short hash of the deployment rather than having a cached version for each pod
> Tie css cache to version of application

- server/data/restClient.test.ts
- server/data/restClient.ts
- server/sanitisedError.test.ts
- server/sanitisedError.ts
It doesn't really make sense to retry non-idempotent calls - there is a risk of double creating resources.
Also moving sanitised error over to a real error rather than an object. Makes it a little bit easier to test these: `expect(..).reject.throws` etc.. doesn't work if you don't have real errors
> Do not retry POST requests by default

- .circleci/config.yml
- CHANGELOG.md
- Dockerfile
- integration_tests/e2e/health.cy.ts
- integration_tests/mockApis/tokenVerification.ts
- server/applicationInfo.ts
- server/config.ts
- server/data/healthCheck.test.ts
- server/data/healthCheck.ts
- server/middleware/setUpHealthChecks.ts
- server/routes/testutils/appSetup.ts
- server/services/healthCheck.test.ts
- server/services/healthCheck.ts
Attempt to bring health and info endpoints inline with the Kotlin template.
> HEAT-106: Standardise endpoints

- integration_tests/e2e/health.cy.ts
- server/services/healthCheck.test.ts
- server/services/healthCheck.ts
Change so that we always return `status` to match spring boot.
e.g. spring boot returns:
```json
"restrictedPatientsApi": {
"details": {
"error": "org.springframework.web.reactive.function.client.WebClientRequestException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8095"
},
"status": "DOWN"
}
```
and we now return 
```json
"hmppsAuth": {
"status": "DOWN",
"details": {
"status": 500,
"response": {
"req": {
"method": "GET",
"url": "http://localhost:9091/auth/health/ping",
"headers": {}
},
"header": {
"matched-stub-id": "7f0f22d4-26f1-4d8a-ac83-9c2aa09729cb",
"transfer-encoding": "chunked"
},
"status": 500,
"text": ""
},
"retries": 2
}
},
```
> SDIT-1088: ✨ Get components to always return status even if failed

- CHANGELOG.md
- integration_tests/e2e/health.cy.ts
- integration_tests/mockApis/manageUsersApi.ts
- server/services/healthCheck.ts
I think this was missed off from #247 when moving a couple of calls from HMPPS Auth to HMPPS Manage Users
> HAAR-1891: Add newly-included Manage Users api to health checks

- helm_deploy/hmpps-template-typescript/Chart.yaml
- helm_deploy/hmpps-template-typescript/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
> Migrating project to use groups in allowlist

- server/data/manageUsersApiClient.test.ts
- server/data/manageUsersApiClient.ts
- server/services/userService.test.ts
- server/services/userService.ts
- server/testutils/createUserToken.ts
- Remove getUserRoles as an api call and get roles by decoding the token
- Add roles to the getUser(token) service method
- Update tests
This significantly reduces the number of calls needed to external services. In this case the api method getUserRoles(token) merely sends the token off to the manage-users-api which decodes it and sends back the result.
> Remove getUserRoles as an api call and add as decoded from the token

- integration_tests/mockApis/manageUsersApi.ts
- server/data/manageUsersApiClient.ts
1 ) Removed staffId (userId has same info),
2) activeCaseLoadId : can be derived from 'me/caseloads' endpoint in 'nomis-user-roles-api'
> HAAR-2061: Remove deprecated filed

- server/views/partials/breadcrumb.njk
Adds a toggle - defaulting to true. To include or leave off the current page title from the breadcrumb partial.
> Update the breadcrumb partial with display current page title toggle

- package-lock.json
- package.json
- renovate.json
- server/middleware/setUpStaticResources.ts
- server/views/partials/layout.njk
Might be worth noting that cypress still bundles jquery so it will remain available for integration tests
> Update MoJ frontend, dropping jQuery which is no longer required

- server/utils/nunjucksSetup.ts
`node_modules/govuk-frontend/dist/components/` was missing `govuk/`
before `components/`, however we don't really need both the higher-level
and lower-level paths here. For greater consistency, just using the
higher-level path to enable a single clearly-namespaced route to each
GOV.UK and MOJ Nunjucks component makes more sense. The lower-level path
is often unused on projects that use this template
Imports should therefore look like this:
```njk
{% from "govuk/components/checkboxes/macro.njk" import govukCheckboxes %}
```
... and not this:
```njk
{% from "checkboxes/macro.njk" import govukCheckboxes %}
```
> Update Nunjucks component paths

- .circleci/config.yml
- CHANGELOG.md
> Setting node version for security audit and outdated

- esbuild/esbuild.config.js
- Fixed issue where .env files are not preloaded when using the new ESBuild watch setup
> Add dotenv to ESBuild server watch

- .circleci/config.yml
- .eslintrc.json
- .gitignore
- README.md
- esbuild/app.config.js
- esbuild/assets.config.js
- esbuild/esbuild.config.js
- esbuild/index.d.ts
- package-lock.json
- package.json
- server/middleware/setUpStaticResources.ts
The idea is to improve changes from [hmpps-template-typescript#375](https://github.com/ministryofjustice/hmpps-template-typescript/pull/375) by:
- removing vestigial references to paths that are no longer used for building assets
- removing now-unused direct dev dependencies
- removing superfluous routes to static asset (there shouldn’t be multiple routes/urls to the same files)
- adding JSDoc-based typing information to esbuild scripts – while this does not _enforce_ correct types, it helps IDEs warn of errors
- preventing esbuild steps exiting on error so that, in watch mode, the parent process lives on; based on [hmpps-sentence-plan-ui#35](https://github.com/ministryofjustice/hmpps-sentence-plan-ui/pull/35)
- using `process.stderr.write` in place of `console.*` to not require eslint …
> Tidy up esbuild processes

- server/utils/nunjucksSetup.ts
When running unit tests, the app runs from outside the compiled `/dist/` folder so the manifest.json file cannot be found. This floods test output with error messages which don’t really matter.
Eg. [CircleCI build job for this project](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-template-typescript/2910/workflows/52194750-3015-48f6-87d2-c68097b11aae/jobs/11097#step-103-12521_81)
This is an inelegant hack to silence them. `jest` tests don’t actually try to load any assets; there is no server running.
Alternatively, the `assetManifest` variable be conditional depending on where the code executes from, but that feels a bit unreliable…
> Silence asset manifest file error during tests

- .env.example
- README.md
- docker-compose.yml
- server/config.ts
I've added a set of client credentials into the hmpps-auth seed database that can be used by anyone running docker locally.
* Fixed an issue where we can't create sessions when running in docker compose due to https only flag.
* Adding example.env file to allow running locally using npm.
* Fix issue with missing redis hostname in docker-compare
* Improve docs
> Supporting starting a fresh application

- .github/workflows/pipeline.yml
Add a few lines to the overall pipeline to cancel existing workflows, or wait if it's main.
This is the same as the default in CircleCI:
_Auto-cancel redundant workflows
With the exception of your default branch, we will automatically cancel any outstanding workflows on a branch when a newer pipeline is triggered on that branch. Scheduled workflows and re-runs are not auto-canceled._
> HEAT-417 - cancel existing running workflows for non-main pipelines

- esbuild/esbuild.config.js
In the context of the esbuild routine, the current approach to watching for file changes means that, when running a development server, a new server process is created and killed for _every single file found in the `dist` directory_. I have [replicated this with useful logging on a branch of our own repository](https://github.com/ministryofjustice/hmpps-approved-premises-ui/tree/esbuild-proceses-spawn-count), for which we've recently back-ported the template's esbuild config: when running the `npm run start:dev` command, you will see hundreds of `Started new server process with pid ...` being logged to the console.
This isn't an issue in itself (as long as we're happy that starting/killing processes willy-nilly is fine 😄), but, should you decide to keep your server running, while also …
> Only restart dev server once esbuild complete

- package.json
- server/data/index.ts
- tsconfig.json
Had this pop up:
```ts-jest[config] (WARN) "isolatedModules" is deprecated and will be removed in v30.0.0. Please remove "isolatedModules" from your "ts-jest" transform options and enable "isolatedModules: true" in /Users/paul.solecki/moj/hmpps-content-hub-feedback-reports/tsconfig.json instead.```
This updates as suggested.
> Change deprecated tsconfig option

- .github/workflows/security_npm_dependency.yml
- .github/workflows/security_trivy.yml
- .github/workflows/security_veracode_pipeline_scan.yml
- .github/workflows/security_veracode_policy_scan.yml
Using CodeQL to scan Github Workflows reports issues with missing permissions.
These explicit permissions enable the scans to run without alerting.
> add discrete permissions for CodeQL scans

- .github/workflows/pipeline.yml
Having it set to true is useful if people are running the image locally.
However the vast majority of our images are never run locally and thus consume double the amount of storage space and take double the amount of computing power to build. Therefore, for the purposes of green computing, it would be better to set the default to false and people can enable in their repos if required.
> SDIT-2788: 🔧 Default multi platform to false
